export type Lang = "en" | "sn";

const en = {
  sent: "Sent",
  inTransit: "In transit",
  ready: "Ready to collect",
  collected: "Collected",
  waitingPay: "Waiting for PEP",
  readyNotice: "Your money is ready to collect.",
  readyNoticeSn: "Mari yako yagadzirira kutambirwa.",
  notReadyYet: "Sent. Not ready to collect yet.",
  onTheWay: "The money is moving. Amai cannot collect it yet.",
  nothingNew: "Nothing new for October.",
  screenshot: "A voucher shows up here only after Thandi's payment is real. A screenshot is not a payment.",
  screenshotSn: "Nhamba yekutora inoonekwa chete kana mari yasvika. Screenshot haisi mari.",
  september: "September · collected",
  mhoroAmai: "Mhoro, Amai.",
  phoneChanges: "This phone only changes when the money is real.",
  voucherLabel: "Mukuru voucher",
  sameSeptember: "Same as September · R2 000",
  differentAmount: "Different amount",
  cashBooth: "Cash at a booth",
  herWallet: "Her wallet",
  boothCash: "Booth cash",
  payCard: "Pay {amount} from the card",
  payPep: "Pay cash at PEP instead",
  payHint: "The card is charged once. PEP does not tell Amai until the till confirms the cash.",
  lockRate: "Lock this rate",
  locking: "Locking…",
  back: "Back",
  typeAmount: "Or type an amount",
  earlier: "Earlier sends",
  heldKicker: "Held on this phone",
  heldTitle: "Your money has not left the card.",
  heldBody: "Amai has not been told. When the signal is back, this same order is sent. It is not a second charge.",
  resume: "Type PIN for this same order",
  stillSending: "Still sending…",
  leaveUnsent: "Leave it unsent",
  receiptSent: "Sent",
  receiptWaiting: "Waiting for PEP",
  forAmai: "{usd} for Amai",
  inWalletNote: "It will be ready to collect in her Mukuru Wallet. Cash-out at a booth is free.",
  cashNote: "She collects the notes with her ID and this number, once it is ready.",
  pepNote: "Pay this number at PEP. Amai has no voucher until the cash is confirmed.",
  cardCharged: "Card charged {amount}.",
  cardNotCharged: "The card was not charged. PEP takes the cash.",
  copyWhatsapp: "Copy WhatsApp",
  copied: "Copied",
  amaiPage: "Amai's page",
  thisAndroid: "This Android",
  ussd: "USSD *120#",
  paydayLine: "Payday is on the card. You do not need to phone anyone.",
  everyMonth: "Harare · mother · every month",
  liveRate: "Live rate",
  rateLocked: "Rate locked",
  estimate: "Estimate",
  amaiReceives: "Amai receives",
  leavesCard: "Leaves your card",
  feeInside: "Mukuru fee, inside that",
  rateOnTransfer: "Rate on this transfer",
  screenRate: "Screen rate today",
  shePays: "She pays to collect",
  landsIn: "Lands in",
  walletLand: "Her Mukuru Wallet",
  boothLand: "Cash at the Orange Booth, Borrowdale",
  screenWould: "Screen rate would pay about {usd}.",
  lockedUntil: "Locked until {time}.",
  notLocked: "Not locked yet.",
  pinTitle: "Mukuru Card PIN",
  pinPep: "PIN to start the PEP order",
  pinHelp: "Demo PIN 2580. The card is charged only after this PIN.",
  notNow: "Not now",
  send: "Send",
  sending: "Sending…",
  haveCash: "I have the cash",
  intro:
    "Mhoro, Thandi. Payday. September reached Amai on {date}. She got {usd} in her wallet, and she has collected it. Send October the same way?",
  introEmpty: "Mhoro, Thandi. Send money home when you are ready.",
  saidSame: "Same as September. R2 000 to her wallet.",
  saidAmount: "{amount} to {where}.",
  whereWallet: "her wallet",
  whereBooth: "a booth",
  words: "Words",
  icons: "Icons",
  english: "English",
  shona: "ChiShona",
  fromThandiCard: "From Thandi · {amount} left her card.",
  fromThandiPep: "From Thandi · paid in cash at PEP. The card was not used.",
  idOnFile: "ID on file {id}.",
  freeCashout: "Taking the notes at an Orange Booth is free on this transfer.",
  bringId: "Bring the ID that says Rudo Ncube.",
  bringIdSn: "Uya neID inoti Rudo Ncube. Kutora hakubhadharwi.",
  walletSn: "Mari iri muWallet. Kubuda kwemari pabooth hakubhadharwi.",
  noPin: "Mukuru will not phone you to ask for a PIN, a card number, or this voucher.",
  noPinSn: "Mukuru haikumbiri PIN panhare.",
  looking: "Looking for a voucher…",
  amountError: "Use an amount from R100 to R5 000, like 1500 or 1500.50.",
  rateMoved: "The rate has moved. Yours is still locked.",
  collectedBtn: "I have collected it",
  notPaidTitle: "Mukuru has not been paid.",
  notPaidBody: "There is no collection number until the cash is confirmed.",
  movingTitle: "On the way",
  ussdLive: "Live Mukuru is *130*567#",
  ussdSend: "1 Send home",
  ussdFinish: "1 Finish the same order",
  ussdLast: "2 Last send",
  ussdHelp: "3 Help",
  ussdSame: "1 Same as Sep  R2000",
  ussdOther: "2 Other amount",
  ussdWallet: "1 Her wallet",
  ussdBooth: "2 Cash at booth",
  ussdPayCard: "1 Pay from card",
  ussdPayPep: "2 Pay at PEP",
  ussdBack: "0 Back",
  ussdMenu: "0 Menu",
  ussdAmaiGets: "Amai gets",
  ussdYouPay: "You pay",
  ussdFee: "Fee",
  ussdEnterPin: "Enter PIN",
  ussdNotReady: "Amai is told when it is\nready to collect.",
  ussdNoVoucher: "Amai has no voucher\nuntil PEP is paid.",
  ussdWorking: "Working… do not press again.",
  ussdHeldBody: "HELD ON PHONE\nMoney has not left.\nAmai has not been told.\nSame order when signal returns.",
  ussdNoSignal: "NO SIGNAL\nRate not locked.\nCard not touched.",
  ussdNotSent: "Not sent. Nothing was charged.",
  ussdHelpBody: "Voucher + ID to collect.\nBooth collection is free.\nMukuru will not ask\nfor a PIN by phone.",
  ussdAmount: "Amount in rands",
  ussdTypeOk: "Type, then OK",
  ussdDemoPin: "Demo 2580",
  ussdOkSend: "OK to send",
  ussdLastTitle: "Last send",
  ussdNone: "No send yet.",
  ussdWrongPin: "Wrong PIN. Money stayed.",
  noSignalLock: "The rate cannot lock with no signal. Your card has not been touched.",
  badAmount: "That amount cannot be sent. Stay between R100 and R5 000.",
  rateLockedSlow: "Rate locked. It was slow, and it went through once.",
  signalDropped: "The signal dropped before the rate could lock. Your card has not been touched.",
  thinSignal: "The signal is thin. This is still working. Do not tap again.",
  badPin: "That PIN is wrong. The money stayed on the card.",
  quoteExpired: "Those 15 minutes ran out. Lock the rate again. Nothing was charged.",
  insufficient: "The card does not have enough for this amount. Nothing was charged.",
  quoteUsed: "This quote was already used. Check the send below before trying again.",
  sendFailed: "That send did not go through. Nothing was charged.",
  heldNotice: "Held on this phone. Your money has not left the card, and Amai has not been told.",
} as const;

const sn: Record<keyof typeof en, string> = {
  sent: "Yatumirwa",
  inTransit: "Iri munzira",
  ready: "Yagadzirira kutambirwa",
  collected: "Yatambirwa",
  waitingPay: "Tichimirira PEP",
  readyNotice: "Mari yako yagadzirira kutambirwa.",
  readyNoticeSn: "Your money is ready to collect.",
  notReadyYet: "Yatumirwa. Haisati yagadzirira kutambirwa.",
  onTheWay: "Mari iri munzira. Amai havasati vagona kuitambira.",
  nothingNew: "Hakuna chitsva cheOctober.",
  screenshot: "Nhamba inoonekwa chete kana mari yasvika. Screenshot haisi mari.",
  screenshotSn: "A voucher shows up only after the payment is real.",
  september: "September · yatambirwa",
  mhoroAmai: "Mhoro, Amai.",
  phoneChanges: "Foni iyi inoshanduka chete kana mari yava yechokwadi.",
  voucherLabel: "Voucher yeMukuru",
  sameSeptember: "Saka seSeptember · R2 000",
  differentAmount: "Mari yakasiyana",
  cashBooth: "Cash pabooth",
  herWallet: "Wallet yake",
  boothCash: "Cash pabooth",
  payCard: "Bhadhara {amount} neKadhi",
  payPep: "Bhadhara cash paPEP",
  payHint: "Kadhi inobhadharwa kamwe chete. Amai havaudzwa kusvika PEP yabhadhara.",
  lockRate: "Vhara mutengo uyu",
  locking: "Tiri kuvhara…",
  back: "Dzoka",
  typeAmount: "Kana nyora mari",
  earlier: "Zvakatumirwa kare",
  heldKicker: "Yakagarwa pafoni iyi",
  heldTitle: "Mari haisati yabuda paKadhi.",
  heldBody: "Amai havasati vaudzwa. Kana network yadzoka, order imwe chete iyi ndiyo inotumirwa.",
  resume: "Isa PIN yeorder imwe chete iyi",
  stillSending: "Ichiri kutumira…",
  leaveUnsent: "Siya isina kutumirwa",
  receiptSent: "Yatumirwa",
  receiptWaiting: "Tichimirira PEP",
  forAmai: "{usd} kuna Amai",
  inWalletNote: "Ichazogadzirira kutambirwa muMukuru Wallet. Kubuda pabooth hakubhadharwi.",
  cashNote: "Vanotora cash neID nenhamba iyi, kana yagadzirira.",
  pepNote: "Bhadhara nhamba iyi paPEP. Amai havana voucher kusvika cash yabhadharwa.",
  cardCharged: "Kadhi yabhadharwa {amount}.",
  cardNotCharged: "Kadhi haina kubhadharwa. PEP inotora cash.",
  copyWhatsapp: "Kopa WhatsApp",
  copied: "Yakopwa",
  amaiPage: "Peji yaAmai",
  thisAndroid: "Android iyi",
  ussd: "USSD *120#",
  paydayLine: "Muhoro uri paKadhi. Haufaniri kufona.",
  everyMonth: "Harare · amai · mwedzi wese",
  liveRate: "Mutengo wezvino",
  rateLocked: "Mutengo wakavharwa",
  estimate: "Fungidziro",
  amaiReceives: "Amai vanowana",
  leavesCard: "Inobuda paKadhi",
  feeInside: "Mari yebasa, mukati",
  rateOnTransfer: "Mutengo wekutumira uku",
  screenRate: "Mutengo wescreen nhasi",
  shePays: "Haabhadhari kutora",
  landsIn: "Inosvika",
  walletLand: "Mukuru Wallet yake",
  boothLand: "Cash paOrange Booth, Borrowdale",
  screenWould: "Mutengo wescreen ungapa {usd}.",
  lockedUntil: "Wakavharwa kusvika {time}.",
  notLocked: "Hausati wavharwa.",
  pinTitle: "PIN yeMukuru Card",
  pinPep: "PIN yekutanga order yePEP",
  pinHelp: "PIN yedemo ndi 2580. Kadhi inobhadharwa chete mushure mePIN.",
  notNow: "Kwete izvozvi",
  send: "Tumira",
  sending: "Tiri kutumira…",
  haveCash: "Ndatora mari",
  intro:
    "Mhoro, Thandi. Musi wemuhoro. September yakasvika kuna Amai musi wa{date}. Vakawana {usd} muWallet, uye vakatotambira. Tumira October nenzira imwe chete?",
  introEmpty: "Mhoro, Thandi. Tumira mari kumba kana wagadzirira.",
  saidSame: "Saka seSeptember. R2 000 kuWallet yake.",
  saidAmount: "{amount} ku{where}.",
  whereWallet: "wallet yake",
  whereBooth: "booth",
  words: "Mashoko",
  icons: "Zvifananidzo",
  english: "English",
  shona: "ChiShona",
  fromThandiCard: "Kubva kuna Thandi · {amount} yabuda paKadhi.",
  fromThandiPep: "Kubva kuna Thandi · yabhadharwa cash paPEP.",
  idOnFile: "ID iri pafaira {id}.",
  freeCashout: "Kutora manotsi paOrange Booth hakubhadharwi.",
  bringId: "Uya neID inoti Rudo Ncube.",
  bringIdSn: "Bring the ID that says Rudo Ncube.",
  walletSn: "This is in her Mukuru Wallet. Booth cash-out is free.",
  noPin: "Mukuru haidaviri kuti ukumbire PIN panhare.",
  noPinSn: "Mukuru will not phone you to ask for a PIN.",
  looking: "Tiri kutarisa nhamba…",
  amountError: "Shandisa mari kubva R100 kusvika R5 000.",
  rateMoved: "Mutengo washanduka. Wako uchiri wakavharwa.",
  collectedBtn: "Ndatambira",
  notPaidTitle: "Mukuru haisati yabhadharwa.",
  notPaidBody: "Hapana nhamba yekutora kusvika cash yabhadharwa.",
  movingTitle: "Iri munzira",
  ussdLive: "Mukuru chaiyo ndi *130*567#",
  ussdSend: "1 Tumira kumba",
  ussdFinish: "1 Pedzisa order imwe chete",
  ussdLast: "2 Yekupedzisira",
  ussdHelp: "3 Rubatsiro",
  ussdSame: "1 Saka seSep  R2000",
  ussdOther: "2 Mari imwe",
  ussdWallet: "1 Wallet yake",
  ussdBooth: "2 Cash pabooth",
  ussdPayCard: "1 Bhadhara neKadhi",
  ussdPayPep: "2 Bhadhara paPEP",
  ussdBack: "0 Dzoka",
  ussdMenu: "0 Menyu",
  ussdAmaiGets: "Amai vanowana",
  ussdYouPay: "Unobhadhara",
  ussdFee: "Fee",
  ussdEnterPin: "Isa PIN",
  ussdNotReady: "Amai vanoudzwa kana\nyagadzirira kutambirwa.",
  ussdNoVoucher: "Amai havana voucher\nkusvika PEP yabhadhara.",
  ussdWorking: "Iri kushanda… usadzvanya zvakare.",
  ussdHeldBody: "YAKAGARWA PAFONI\nMari haisati yabuda.\nAmai havasati vaudzwa.\nOrder imwe chete kana network yadzoka.",
  ussdNoSignal: "HAPANA NETWORK\nMutengo hausati wavharwa.\nKadhi haina kubatwa.",
  ussdNotSent: "Haina kutumirwa. Hapana chakabhadharwa.",
  ussdHelpBody: "Voucher neID yekutambira.\nKutora pabooth hakubhadharwi.\nMukuru haikumbiri\nPIN panhare.",
  ussdAmount: "Mari mumadhora eRand",
  ussdTypeOk: "Nyora, wobva wazvanya OK",
  ussdDemoPin: "Demo 2580",
  ussdOkSend: "OK kutumira",
  ussdLastTitle: "Yekupedzisira",
  ussdNone: "Hapana chakatumbirwa.",
  ussdWrongPin: "PIN haina kunaka. Mari yakagara.",
  noSignalLock: "Mutengo haugone kuvharwa pasina network. Kadhi haina kubatwa.",
  badAmount: "Mari iyoyo haikwanisi kutumirwa. R100 kusvika R5 000.",
  rateLockedSlow: "Mutengo wakavharwa. Yakanonoka, asi yakapinda kamwe.",
  signalDropped: "Network yakadonha. Kadhi haina kubatwa.",
  thinSignal: "Network iri diki. Iri kushanda. Usadzvanya zvakare.",
  badPin: "PIN haina kunaka. Mari yakagara paKadhi.",
  quoteExpired: "Maminitsi 15 apera. Vhara mutengo zvakare. Hapana chakabhadharwa.",
  insufficient: "Kadhi haina mari yakakwana. Hapana chakabhadharwa.",
  quoteUsed: "Mutengo uyu wakatoshandiswa. Tarisa kutumira kwazvino.",
  sendFailed: "Haina kutumirwa. Hapana chakabhadharwa.",
  heldNotice: "Yakagarwa pafoni. Mari haisati yabuda, uye Amai havasati vaudzwa.",
};

export type CopyKey = keyof typeof en;

export function t(lang: Lang, key: CopyKey, vars?: Record<string, string>) {
  const raw = (lang === "sn" ? sn[key] : en[key]) || en[key];
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, name: string) => vars[name] ?? "");
}
